#' Reproducible R code export
#'
#' Turns an analysis session into a standalone, runnable R script that
#' reproduces the pipeline with RNAflow's public functions -- ready to drop
#' into a Methods section or a supplementary file. Pure string generation,
#' no side effects.
#'
#' @name export_code
#' @keywords internal
NULL

#' Sanitize a contrast label into a valid R object suffix
#' @keywords internal
r_name <- function(x) {
  x <- gsub("[^A-Za-z0-9]+", "_", x)
  x <- gsub("^_+|_+$", "", x)
  if (!nzchar(x)) x <- "contrast"
  x
}

# Quote a value as a safe R double-quoted string literal (escapes embedded
# quotes and backslashes) for insertion into the generated script.
q_str <- function(x) encodeString(as.character(x), quote = "\"")

#' Generate a reproducible R script for an analysis
#'
#' @param project a project list (from [empty_project()] / the app session);
#'   uses `$organism` and `$contrasts` (the contrast store)
#' @param counts_path,metadata_path paths written into the `read_*` calls
#' @param generated optional timestamp string to stamp in the header
#' @return a single character string containing the R script
#' @export
generate_r_script <- function(project,
                              counts_path = "counts.csv",
                              metadata_path = "metadata.csv",
                              generated = NULL) {
  organism <- project$organism %||% "human"
  store    <- project$contrasts %||% list()
  ver <- tryCatch(as.character(utils::packageVersion("RNAflow")),
                  error = function(e) "dev")

  L <- character(0)
  add <- function(...) L <<- c(L, ...)

  add(sprintf("# RNAflow reproducible analysis script"),
      sprintf("# Generated by RNAflow v%s%s", ver,
              if (!is.null(generated)) paste0(" on ", generated) else ""),
      "# DE calls reflect each saved contrast (design, covariates, shrinkage).",
      "# Enrichment / WGCNA use the settings actually run when those were",
      "# recorded; otherwise example defaults are emitted -- edit as needed.",
      "",
      "library(RNAflow)",
      "",
      "## 1. Load and validate inputs -------------------------------------------",
      sprintf("counts   <- read_counts(%s)", q_str(counts_path)),
      sprintf("meta     <- read_metadata(%s, counts_samples = colnames(counts))",
              q_str(metadata_path)),
      sprintf("organism <- %s", q_str(organism)),
      "")

  # ---- Differential expression, one call per stored contrast ----
  add("## 2. Differential expression (DESeq2) -----------------------------------")
  var_names <- character(0)
  computed  <- logical(0)
  if (length(store) == 0) {
    add("# No contrasts were saved in this session; template call below:",
        "res_1 <- run_deseq2(counts, meta, design = ~condition,",
        '                    contrast = c("condition", "Treatment", "Control"))')
    var_names <- "res_1"; computed <- TRUE
  } else {
    # Unique object name per contrast: distinct labels can sanitise to the same
    # suffix, so disambiguate to stop two `res_*` objects from clashing.
    all_vn <- make.unique(
      paste0("res_", vapply(names(store), r_name, character(1))), sep = "_")
    for (i in seq_along(store)) {
      lbl <- names(store)[i]
      p <- store[[i]]$params %||% list()
      vn <- all_vn[i]
      var_names <- c(var_names, vn)
      is_computed <- !is.null(p$design_var)
      computed <- c(computed, is_computed)
      if (is_computed) {
        design_terms <- c(p$covariates, p$design_var)   # covariates first
        add(sprintf("# %s", lbl),
            sprintf("%s <- run_deseq2(", vn),
            "  counts, meta,",
            sprintf("  design   = ~%s,",
                    paste(sprintf("`%s`", design_terms), collapse = " + ")),
            sprintf("  contrast = c(%s, %s, %s),",
                    q_str(p$design_var), q_str(p$treated), q_str(p$reference)),
            sprintf("  shrink = %s, min_count = %s, alpha = %s",
                    isTRUE(p$shrink), p$min_count %||% 10, p$alpha %||% 0.05),
            ")", "")
      } else {
        # Uploaded DE table: RNAflow cannot recompute it. Define the object via
        # a real (user-completed) read call so downstream steps stay valid.
        add(sprintf("# %s (uploaded DE table -- RNAflow cannot recompute it)", lbl),
            sprintf("%s <- read_de_results(%s)", vn,
                    q_str("PATH_TO_YOUR_DE_TABLE.csv")), "")
      }
    }
  }
  add("")

  # ---- Figures + multi-contrast ----
  # Anchor the figure/enrichment examples on a contrast RNAflow actually
  # computed (falling back to the first if all were uploaded).
  ex <- if (any(computed)) var_names[which(computed)[1]] else var_names[1]
  add("## 3. Figures & multi-contrast comparison -------------------------------",
      sprintf("p_volcano <- fig_volcano(%s, lfc_thr = 1, padj_thr = 0.05,", ex),
      '                         mode = "publication")',
      'save_ggplot(p_volcano, "volcano.pdf", "pdf", w = 5, h = 4)',
      "")
  if (length(var_names) >= 2) {
    items <- paste(sprintf('  `%s` = %s', names(store), var_names),
                   collapse = ",\n")
    add("# Compare contrasts",
        paste0("contrasts <- list(\n", items, "\n)"),
        "fig_upset(contrast_sig_sets(contrasts, padj_thr = 0.05, lfc_thr = 1))",
        'fig_lfc_heatmap(contrasts, gene_src = "sig_union")',
        "")
  }

  # ---- Enrichment (exact settings when recorded, else a template) ----
  add("## 4. Functional enrichment ---------------------------------------------")
  en <- project$enrichment
  if (is.list(en) && length(en) && !is.null(en$method) && en$method == "gsea") {
    sub <- if (!is.null(en$subcollection))
      sprintf(', subcollection = "%s"', en$subcollection) else ""
    add(sprintf('gene_sets <- get_gene_sets(organism, collection = "%s"%s)',
                en$collection, sub),
        sprintf('gsea <- run_gsea(%s, gene_sets, rank_by = "%s")', ex, en$rank_by),
        "fig_enrich_dot(gsea)", "")
  } else if (is.list(en) && length(en) && !is.null(en$method) && en$method == "ora") {
    add(sprintf('sig <- contrast_sig_genes(%s, padj_thr = %s, lfc_thr = %s, direction = "%s")',
                ex, en$padj %||% 0.05, en$lfc %||% 1, en$direction %||% "either"),
        sprintf('ora <- run_ora(sig, organism, db = "%s", ont = "%s", universe = %s$gene)',
                en$db %||% "GO", en$ont %||% "BP", ex),
        "fig_enrich_bar(ora)", "")
  } else {
    add("# (no enrichment run recorded -- example with default settings)",
        'gene_sets <- get_gene_sets(organism, collection = "H")',
        sprintf('gsea <- run_gsea(%s, gene_sets, rank_by = "stat")', ex),
        "fig_enrich_dot(gsea)",
        sprintf('sig <- contrast_sig_genes(%s, padj_thr = 0.05, lfc_thr = 1)', ex),
        sprintf('ora <- run_ora(sig, organism, db = "GO", ont = "BP", universe = %s$gene)', ex),
        "fig_enrich_bar(ora)", "")
  }

  # ---- WGCNA (exact settings when recorded, else a template) ----
  norm_line <- if (identical(project$normalization_method,
                             "log2(counts+1) [VST fallback]"))
    "norm    <- log2(counts + 1)  # VST failed in the original session; log2 fallback"
  else 'norm    <- normalize_counts(counts, meta, method = "vst")'
  add("## 5. Co-expression network (WGCNA) -------------------------------------",
      norm_line)
  wg <- project$wgcna
  if (is.list(wg) && length(wg) && !is.null(wg$power)) {
    add(sprintf("datExpr <- wgcna_datexpr(norm, n_genes = %s)", wg$n_genes %||% 3000),
        sprintf('wg <- run_wgcna(datExpr, power = %s, network_type = "%s",',
                wg$power, wg$network_type %||% "signed"),
        sprintf("                min_module_size = %s, merge_cut_height = %s, deep_split = %s)",
                wg$min_module_size %||% 30, wg$merge_cut_height %||% 0.25,
                wg$deep_split %||% 2))
  } else {
    add("# (no module run recorded -- example with an auto-picked power)",
        "datExpr <- wgcna_datexpr(norm, n_genes = 3000)",
        "sft     <- wgcna_pick_power(datExpr)",
        "wg      <- run_wgcna(datExpr, power = sft$suggested)")
  }
  add("traits  <- build_traits(meta, rownames(datExpr))",
      "fig_module_trait(module_trait_cor(wg$MEs, traits))",
      "")

  # ---- Signatures (GSVA/ssGSEA): exact collection/method when recorded ----
  add("## 6. Signatures (GSVA / ssGSEA) ---------------------------------------",
      "# NOTE: the app maps gene IDs to symbols before scoring; ensure",
      "#       rownames(norm) are gene symbols to reproduce this exactly.")
  sg <- project$signatures
  if (is.list(sg) && length(sg) && !is.null(sg$collection)) {
    cc  <- ENRICH_COLLECTIONS[[sg$collection]]
    sub <- if (!is.null(cc$sub)) sprintf(', subcollection = "%s"', cc$sub) else ""
    add(sprintf('gene_sets <- get_gene_sets(organism, collection = "%s"%s)',
                cc$collection %||% "H", sub),
        sprintf('scores    <- run_gsva(norm, gene_sets, method = "%s")',
                sg$method %||% "gsva"),
        "fig_gsva_heatmap(scores, meta)", "")
  } else {
    add("# (no signatures run recorded -- example with Hallmark + GSVA)",
        'gene_sets <- get_gene_sets(organism, collection = "H")',
        'scores    <- run_gsva(norm, gene_sets, method = "gsva")',
        "fig_gsva_heatmap(scores, meta)", "")
  }

  # ---- Regulator / pathway activity (decoupleR): exact settings when recorded ----
  add("## 7. Regulator / pathway activity (decoupleR) --------------------------",
      "# NOTE: activity inference uses gene symbols; ensure the DE table's genes",
      "#       are symbols to reproduce this exactly.")
  ac <- project$activity
  if (is.list(ac) && length(ac) && !is.null(ac$type)) {
    is_tf <- identical(ac$type, "tf")
    add(sprintf("network  <- %s",
                if (is_tf) "get_tf_network(organism)" else "get_pathway_network(organism)"),
        sprintf('activity <- run_activity(%s, network, method = "%s", mor_col = "%s", by = "%s")',
                ex, ac$method %||% (if (is_tf) "ulm" else "mlm"),
                if (is_tf) "mor" else "weight", ac$rank_by %||% "stat"),
        "fig_activity_bar(activity)", "")
  } else {
    add("# (no activity run recorded -- example: transcription-factor activity)",
        "network  <- get_tf_network(organism)",
        sprintf('activity <- run_activity(%s, network, method = "ulm", mor_col = "mor", by = "stat")', ex),
        "fig_activity_bar(activity)", "")
  }

  add("## 8. Not reproduced automatically -------------------------------------",
      "# The optional AI-assisted interpretation is not emitted here: it calls an",
      "# external large-language-model API and is non-deterministic, so it is not",
      "# part of the reproducible script. Re-run it interactively if needed.",
      "",
      "## 9. Session information -----------------------------------------------",
      "sessionInfo()",
      "")

  paste(L, collapse = "\n")
}
